### ISSUE TITLE
Function to deactivate listening

### ISSUE THREAD

**Issue by henrikth93** [scribe-org/Scribe-Desktop#15]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Desktop/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Desktop's [Code of Conduct](https://github.com/scribe-org/Scribe-Desktop/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We need to implement a way to disable the app from listening to the keyboard, for example, in the case where you have the app running, but want to write something in a word document which you do not want to translate. As of now, the app will record the keystrokes and place it into the input field.

GUI Documentation: https://book.iced.rs/architecture.html

**Comment by andrewtavis** [comment]
Do we want to switch this over to typing a command to then type into the GUI? Plan is not that what someone is writing will go into the GUI at all times, so maybe we can simulate it and set up hotkeys for translate, plural and conjugate?

**Comment by henrikth93** [comment]
> Do we want to switch this over to typing a command to then type into the GUI? Plan is not that what someone is writing will go into the GUI at all times, so maybe we can simulate it and set up hotkeys for translate, plural and conjugate?

Me and Ryan were thinking of a button that you can toggle, or a keystroke (like ctrl + l maybe?)

**Comment by andrewtavis** [comment]
That sounds great :) Let's have it be triggered by clicking the Scribe icon for now and we can then transition to it being first click Scribe icon for options then click option then type in the GUI :) For now just click the icon and a keystroke though I think would suffice? Or should we do the full user flow?

**Comment by andrewtavis** [comment]
Closed by #17 😊 There's still lots of styling that needs to be done here, but functionality wise it's definitely going in the right direction 🚀 Happy to do a call some time to plan out some issues, @RyanPaulGannon! Hope all's well on your end :)
